### ISSUE TITLE
Image is reversed in Firefox for Android

### ISSUE THREAD

**Issue by stowball** [koenkivits/colorblindsim#3]
Firefox is my main browser on Android, and I'm not sure if it's a Firefox bug, but the camera image is reversed from reality… and it hurts my brain 😂

Chrome works as expected

**Comment by koenkivits** [comment]
O wow, that isn't supposed to happen! :sweat_smile: I have tested Firefox for Android, but I ran into some problems getting my test environment to run on my phone, and I must've broken it since. My guess is that the app thinks it's using the selfie cam, which it has to reverse in order to work like other camera apps (like a mirror, basically).

I'll fix it -- thanks for reporting!

**Comment by koenkivits** [comment]
@stowball It should be fixed now! Can you check if it works for you as well?

**Comment by stowball** [comment]
Fixed. Love your work 💪

**Comment by koenkivits** [comment]
Thanks!
