### ISSUE TITLE
Selfie cam instead of rear cam on iPhone 11 / iOS 13

### ISSUE THREAD

**Issue by roelvangils** [koenkivits/colorblindsim#6]
Today, I've tried using the website again after some time. On my iPhone 11 (running the latest version of iOS), it showed the image of my Selfie camera instead of (one of the) rear cameras. Is that a bug? I don't think it's possible to change the camera from withing the application, is there?

**Comment by koenkivits** [comment]
@roelvangils completely missed your bug report somehow! Sorry for the very late reply.

There's an option to switch cameras if the app detects multiple cameras, but it seems an iOS update broke the camera detection. I'll be looking into it ASAP!

**Comment by koenkivits** [comment]
Related issue and relevant comment I found: https://github.com/zxing-js/library/issues/149#issuecomment-485358381

**Comment by jasoncapriati** [comment]
Hello!

`mediaDevices.enumerateDevices()` returns an array of _connected_ `MediaDeviceInfo` objects which has properties like `deviceId`, `kind` and `label`.

Safari and iOS Safari do not support this spec [1] yet. 

[1] https://developer.mozilla.org/en-US/docs/Web/API/MediaDeviceInfo

**Comment by koenkivits** [comment]
@roelvangils fixed! Thanks for reporting. :)

**Comment by koenkivits** [comment]
@jasoncapriati I'm not quite sure why MDN lists `MediaDeviceInfo` as unsupported. :thinking: 

`enumerateDevices` has been supported since iOS 11 ([MDN also shows this](https://developer.mozilla.org/en-US/docs/Web/API/MediaDevices/enumerateDevices)) and correctly resolves with `MediaDeviceInfo` objects on iOS. The thing is that it used to work _before_ having video permission, but that seems to have changed. I've filed an issue with MDN regarding the compatibility data: https://github.com/mdn/browser-compat-data/issues/6284
